In [2]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import ndimage as ndi
from scipy import misc
from skimage import feature



In [3]:

# Generate noisy image of a square
im = np.zeros((128, 128))
im[32:-32, 32:-32] = 1

im = ndi.rotate(im, 15, mode='constant')
im = ndi.gaussian_filter(im, 4)
im += 0.2 * np.random.random(im.shape)

# Compute the Canny filter for two values of sigma
edges1 = feature.canny(im)
edges2 = feature.canny(im, sigma=3)

# display results
fig, (ax1, ax2, ax3) = plt.subplots(nrows=1, ncols=3, figsize=(8, 3),
                                    sharex=True, sharey=True)

ax1.imshow(im, cmap=plt.cm.gray)
ax1.axis('off')
ax1.set_title('noisy image', fontsize=20)

ax2.imshow(edges1, cmap=plt.cm.gray)
ax2.axis('off')
ax2.set_title('Canny filter, $\sigma=1$', fontsize=20)

ax3.imshow(edges2, cmap=plt.cm.gray)
ax3.axis('off')
ax3.set_title('Canny filter, $\sigma=3$', fontsize=20)

fig.tight_layout()

plt.show()

/Users/justingosses/anaconda/lib/python3.5/site-packages/matplotlib/tight_layout.py:222: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")


In [8]:
# from scipy import misc
# # f = misc.face()
# # misc.imsave('gathers_test.png', f) # uses the Image module (PIL)

# import matplotlib.pyplot as plt
# # plt.imshow(f)
# # plt.show()

In [10]:
## Alternative
from scipy import misc
import glob

for image_path in glob.glob('gather_screenshot.png'):
    image = misc.imread(image_path)
    print(image.shape)
    print(image.dtype)

(930, 238, 4)
uint8


In [12]:
png = []
for image_path in glob.glob("gather_screenshot.png"):
    png.append(misc.imread(image_path))    

im = np.asarray(png)

print('Importing done...', im.shape)

Importing done... (1, 930, 238, 4)


In [13]:
print(im)

[[[[173 220 191 255]
   [175 220 194 255]
   [177 220 199 255]
   ..., 
   [171 224 200 255]
   [167 219 192 255]
   [164 215 188 255]]

  [[206 236 215 255]
   [206 236 219 255]
   [206 236 223 255]
   ..., 
   [203 241 222 255]
   [200 236 219 255]
   [197 232 216 255]]

  [[228 241 228 255]
   [226 239 230 255]
   [224 237 231 255]
   ..., 
   [221 239 228 255]
   [222 238 232 255]
   [222 237 234 255]]

  ..., 
  [[197 183 155 255]
   [203 178 152 255]
   [213 177 155 255]
   ..., 
   [190 155 116 255]
   [136 103  71 255]
   [123  86  60 255]]

  [[190 174 158 255]
   [199 173 157 255]
   [208 172 159 255]
   ..., 
   [193 163 133 255]
   [159 129 100 255]
   [152 118  92 255]]

  [[187 169 159 255]
   [197 170 160 255]
   [206 170 162 255]
   ..., 
   [195 167 142 255]
   [171 142 115 255]
   [168 135 110 255]]]]


In [4]:
gather_sh = misc.imread('gather_screenshot.png')
type(gather_sh)      
plt.imshow(gather_sh)

gather_sh.shape

(930, 238, 4)

In [7]:
gather_sh.dtype

dtype('uint8')

In [8]:
# Compute the Canny filter for two values of sigma
edges1 = feature.canny(im)
edges2 = feature.canny(im, sigma=3)

# display results
fig, (ax1, ax2, ax3) = plt.subplots(nrows=1, ncols=3, figsize=(8, 3),
                                    sharex=True, sharey=True)

ax1.imshow(im, cmap=plt.cm.gray)
ax1.axis('off')
ax1.set_title('noisy image', fontsize=20)

ax2.imshow(edges1, cmap=plt.cm.gray)
ax2.axis('off')
ax2.set_title('Canny filter, $\sigma=1$', fontsize=20)

ax3.imshow(edges2, cmap=plt.cm.gray)
ax3.axis('off')
ax3.set_title('Canny filter, $\sigma=3$', fontsize=20)

fig.tight_layout()

plt.show()

/Users/justingosses/anaconda/lib/python3.5/site-packages/matplotlib/tight_layout.py:222: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
